[package]
name = "wasm-plugin-foo"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
wasm-data = { path = "../wasm-data" }
wasm-plugin-macro = { path = "../wasm-plugin-macro" }
