[package]
name = "wasm-data"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
bincode = "1"
